name: Build All APPs

on:
  push:
    tags:
      - v*

jobs:
  build-spa:
    name: Build SPA application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm install -g quasar
      - run: quasar build
      - run: |
          zip -r spa-${{ github.ref_name }}.zip ./dist/spa
          gh release create '${{ github.ref_name }}' -n "New" spa-${{ github.ref_name }}.zip
